[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 1
via_ir = true
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"
]
fs_permissions = [{ access = "read-write", path = "./deployments" }]

[fuzz]
runs = 256  # Reduced from default 256 for faster testing

[invariant]
runs = 256  # Reduced from default 256 for faster testing
depth = 15  # Max call depth

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
